insert into public.instruments (
  symbol,
  short_name,
  name,
  description,
  market_region,
  exchange,
  currency,
  asset_type,
  isin,
  provider,
  price_source,
  price_source_symbol,
  price_source_exchange,
  price_update_enabled,
  price_update_priority,
  source_url,
  source_checked_at,
  notes
)
values
  (
    'AMD',
    'AMD',
    'Advanced Micro Devices, Inc.',
    'AMD is a semiconductor company focused on high-performance and adaptive computing products, including CPUs, GPUs, data center, gaming, embedded, and AI-related solutions.',
    'US',
    'NASDAQ',
    'USD',
    'stock',
    null,
    'AMD',
    'yahoo_finance',
    'AMD',
    'NASDAQ',
    true,
    1,
    'https://www.amd.com/en/products.html',
    now(),
    null
  ),
  (
    'QQQM',
    'QQQM',
    'Invesco NASDAQ 100 ETF',
    'The Invesco NASDAQ 100 ETF is designed to track the Nasdaq-100 Index and provide exposure to large and mega-cap non-financial companies listed on Nasdaq.',
    'US',
    'NASDAQ',
    'USD',
    'etf',
    null,
    'Invesco',
    'yahoo_finance',
    'QQQM',
    'NASDAQ',
    true,
    1,
    'https://www.invesco.com/us/en/financial-products/etfs/invesco-nasdaq-100-etf.html',
    now(),
    null
  ),
  (
    'VOO',
    'VOO',
    'Vanguard S&P 500 ETF',
    'Vanguard S&P 500 ETF seeks to track the performance of the S&P 500 Index and provides large-cap US equity exposure.',
    'US',
    'NYSE_ARCA',
    'USD',
    'etf',
    null,
    'Vanguard',
    'yahoo_finance',
    'VOO',
    'NYSE_ARCA',
    true,
    1,
    'https://investor.vanguard.com/investment-products/etfs/profile/voo',
    now(),
    null
  ),
  (
    'VGT',
    'VGT',
    'Vanguard Information Technology ETF',
    'Vanguard Information Technology ETF seeks to track a benchmark index measuring the investment return of information technology stocks.',
    'US',
    'NYSE_ARCA',
    'USD',
    'etf',
    null,
    'Vanguard',
    'yahoo_finance',
    'VGT',
    'NYSE_ARCA',
    true,
    1,
    'https://investor.vanguard.com/investment-products/etfs/profile/vgt',
    now(),
    null
  ),
  (
    'SMH',
    'SMH',
    'VanEck Semiconductor ETF',
    'VanEck Semiconductor ETF seeks exposure to US-listed companies involved in semiconductor production and semiconductor equipment.',
    'US',
    'NASDAQ',
    'USD',
    'etf',
    null,
    'VanEck',
    'yahoo_finance',
    'SMH',
    'NASDAQ',
    true,
    1,
    'https://www.vaneck.com/us/en/investments/semiconductor-etf-smh/',
    now(),
    null
  ),
  (
    '01810',
    '小米',
    'Xiaomi Corporation',
    'Xiaomi is a consumer electronics and smart manufacturing company with smartphones and smart hardware connected by an IoT platform at its core, with related internet services.',
    'HK',
    'HKEX',
    'HKD',
    'stock',
    null,
    'Xiaomi',
    'yahoo_finance',
    '1810.HK',
    'HKEX',
    true,
    1,
    'https://ir.mi.com/corporate-information/company-profile',
    now(),
    null
  ),
  (
    '00700',
    '腾讯',
    'Tencent Holdings Limited',
    'Tencent provides value-added services, marketing services, fintech, and business services, with consumer internet and enterprise services across Mainland China and internationally.',
    'HK',
    'HKEX',
    'HKD',
    'stock',
    null,
    'Tencent',
    'yahoo_finance',
    '0700.HK',
    'HKEX',
    true,
    1,
    'https://www.tencent.com/en-us/about.html',
    now(),
    null
  ),
  (
    '161128',
    '标普信息科技',
    '易方达标普信息科技指数证券投资基金（LOF）A（人民币份额）',
    '易方达标普信息科技指数（QDII-LOF）A（人民币份额）是由易方达基金管理有限公司管理、在深圳证券交易所上市交易的 QDII-LOF 人民币份额。',
    'CN',
    'SZSE',
    'CNY',
    'mutual_fund',
    null,
    '易方达基金管理有限公司',
    'eastmoney',
    '161128',
    'SZSE',
    true,
    2,
    'https://cdn.efunds.com.cn/owch/data/bulletin/20250321/%E6%98%93%E6%96%B9%E8%BE%BE%E6%A0%87%E6%99%AE%E4%BF%A1%E6%81%AF%E7%A7%91%E6%8A%80%E6%8C%87%E6%95%B0%E8%AF%81%E5%88%B8%E6%8A%95%E8%B5%84%E5%9F%BA%E9%87%91%EF%BC%88LOF%EF%BC%89%EF%BC%88%E6%98%93%E6%96%B9%E8%BE%BE%E6%A0%87%E6%99%AE%E4%BF%A1%E6%81%AF%E7%A7%91%E6%8A%80%E6%8C%87%E6%95%B0%EF%BC%88QDII-LOF%EF%BC%89A%28%E4%BA%BA%E6%B0%91%E5%B8%81%E4%BB%BD%E9%A2%9D%29%EF%BC%89%E5%9F%BA%E9%87%91%E4%BA%A7%E5%93%81%E8%B5%84%E6%96%99%E6%A6%82%E8%A6%81%E6%9B%B4%E6%96%B0.pdf',
    now(),
    null
  ),
  (
    '159501',
    '纳指100',
    '嘉实纳斯达克100ETF（QDII）',
    '嘉实纳斯达克100ETF（QDII）是嘉实基金管理有限公司管理、在深圳证券交易所上市交易的跨市场 QDII ETF，目标指数代码为 NDX。',
    'CN',
    'SZSE',
    'CNY',
    'etf',
    null,
    '嘉实基金 / Harvest Fund',
    'eastmoney',
    '159501',
    'SZSE',
    true,
    2,
    'https://www.jsfund.cn/Services/cn/jsp/pcf/index.jsp?SiteID=1&fundcode=159501',
    now(),
    null
  ),
  (
    '513500',
    '标普500',
    '博时标普500ETF（QDII）',
    '博时标普500ETF（QDII）是博时基金管理的中国上市 QDII ETF，寻求跟踪或提供标普500指数相关投资表现。',
    'CN',
    'SSE',
    'CNY',
    'etf',
    null,
    '博时基金 / Bosera Asset Management',
    'eastmoney',
    '513500',
    'SSE',
    true,
    2,
    'https://www.sse.com.cn/disclosure/fund/announcement/c/new/2023-08-25/513500_20230825_K8P5.pdf',
    now(),
    null
  ),
  (
    'FS_NASDAQ_100',
    'FS 纳指100',
    'Foundation Series Nasdaq-100 Fund',
    'Foundation Series Nasdaq-100 Fund is a PIE-compliant New Zealand fund that invests into the Invesco NASDAQ 100 ETF and provides exposure to the largest non-financial companies listed on Nasdaq.',
    'NZ',
    'INVESTNOW',
    'NZD',
    'pie_fund',
    null,
    'InvestNow / FundRock NZ',
    'custom',
    'FS_NASDAQ_100',
    'INVESTNOW',
    true,
    3,
    'https://investnow.co.nz/nasdaq/',
    now(),
    null
  ),
  (
    'FS_TOTAL_WORLD',
    'FS 全球',
    'Foundation Series Total World Fund',
    'Foundation Series Total World Fund provides global share exposure through an underlying ETF investing in large, mid-sized, and small companies listed on international stock markets.',
    'NZ',
    'INVESTNOW',
    'NZD',
    'pie_fund',
    null,
    'InvestNow / FundRock NZ',
    'custom',
    'FS_TOTAL_WORLD',
    'INVESTNOW',
    true,
    3,
    'https://investnow.co.nz/fund-manager/investnow-foundation-series/',
    now(),
    null
  ),
  (
    'FS_US_500',
    'FS 标普500',
    'Foundation Series US 500 Fund',
    'Foundation Series US 500 Fund invests into the Vanguard S&P 500 ETF (VOO), providing exposure to 500 of the largest companies in the United States.',
    'NZ',
    'INVESTNOW',
    'NZD',
    'pie_fund',
    null,
    'InvestNow / FundRock NZ',
    'custom',
    'FS_US_500',
    'INVESTNOW',
    true,
    3,
    'https://investnow.co.nz/fund-manager/investnow-foundation-series/',
    now(),
    null
  ),
  (
    'CASH_CNY',
    'CNY现金',
    'CNY Cash',
    'Chinese yuan cash position used for shared family ledger cash balances and cash transactions.',
    'OTHER',
    'CASH',
    'CNY',
    'cash',
    null,
    null,
    'manual',
    'CASH_CNY',
    'CASH',
    false,
    9,
    null,
    now(),
    null
  ),
  (
    'CASH_USD',
    'USD现金',
    'USD Cash',
    'US dollar cash position used for shared family ledger cash balances and cash transactions.',
    'OTHER',
    'CASH',
    'USD',
    'cash',
    null,
    null,
    'manual',
    'CASH_USD',
    'CASH',
    false,
    9,
    null,
    now(),
    null
  ),
  (
    'CASH_NZD',
    'NZD现金',
    'NZD Cash',
    'New Zealand dollar cash position used for shared family ledger cash balances and cash transactions.',
    'OTHER',
    'CASH',
    'NZD',
    'cash',
    null,
    null,
    'manual',
    'CASH_NZD',
    'CASH',
    false,
    9,
    null,
    now(),
    null
  ),
  (
    'CASH_AUD',
    'AUD现金',
    'AUD Cash',
    'Australian dollar cash position used for shared family ledger cash balances and cash transactions.',
    'OTHER',
    'CASH',
    'AUD',
    'cash',
    null,
    null,
    'manual',
    'CASH_AUD',
    'CASH',
    false,
    9,
    null,
    now(),
    null
  ),
  (
    'CASH_HKD',
    'HKD现金',
    'HKD Cash',
    'Hong Kong dollar cash position used for shared family ledger cash balances and cash transactions.',
    'OTHER',
    'CASH',
    'HKD',
    'cash',
    null,
    null,
    'manual',
    'CASH_HKD',
    'CASH',
    false,
    9,
    null,
    now(),
    null
  )
on conflict (market_region, exchange, symbol)
do update set
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  currency = excluded.currency,
  asset_type = excluded.asset_type,
  isin = excluded.isin,
  provider = excluded.provider,
  price_source = excluded.price_source,
  price_source_symbol = excluded.price_source_symbol,
  price_source_exchange = excluded.price_source_exchange,
  price_update_enabled = excluded.price_update_enabled,
  price_update_priority = excluded.price_update_priority,
  source_url = excluded.source_url,
  source_checked_at = excluded.source_checked_at,
  notes = excluded.notes,
  updated_at = now();
