insert into public.instruments (
  symbol,
  short_name,
  name,
  description,
  market_region,
  exchange,
  currency,
  asset_type,
  isin,
  provider,
  price_source,
  price_source_symbol,
  price_source_exchange,
  price_update_enabled,
  price_update_priority,
  source_url,
  source_checked_at,
  notes
)
values (
  'CNDX',
  'CNDX LSE USD',
  'iShares Nasdaq 100 UCITS ETF Acc (LSE USD)',
  'iShares Nasdaq 100 UCITS ETF Acc is the London Stock Exchange USD trading line of the Ireland-domiciled accumulating UCITS ETF tracking the Nasdaq-100 Index.',
  'UK',
  'LSE',
  'USD',
  'etf',
  'IE00B53SZB19',
  'iShares / BlackRock',
  'yahoo_finance',
  'CNDX.L',
  'LSE',
  true,
  1,
  'https://www.ishares.com/uk/individual/en/products/253741/ishares-nasdaq-100-ucits-etf',
  now(),
  'LSE USD accumulating UCITS line.'
)
on conflict (market_region, exchange, symbol)
do update set
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  currency = excluded.currency,
  asset_type = excluded.asset_type,
  isin = excluded.isin,
  provider = excluded.provider,
  price_source = excluded.price_source,
  price_source_symbol = excluded.price_source_symbol,
  price_source_exchange = excluded.price_source_exchange,
  price_update_enabled = excluded.price_update_enabled,
  price_update_priority = excluded.price_update_priority,
  source_url = excluded.source_url,
  source_checked_at = excluded.source_checked_at,
  notes = excluded.notes,
  updated_at = now();
