insert into public.instruments (
  symbol,
  short_name,
  name,
  description,
  market_region,
  exchange,
  currency,
  asset_type,
  isin,
  provider,
  price_source,
  price_source_symbol,
  price_source_exchange,
  price_update_enabled,
  price_update_priority,
  source_url,
  source_checked_at,
  notes
)
values (
  'SMH',
  'SMH LSE USD',
  'VanEck Semiconductor UCITS ETF Acc (LSE USD)',
  'VanEck Semiconductor UCITS ETF Acc is the London Stock Exchange USD trading line of the Ireland-domiciled UCITS accumulating ETF tracking semiconductor companies, distinct from the US-domiciled VanEck Semiconductor ETF.',
  'UK',
  'LSE',
  'USD',
  'etf',
  'IE00BMC38736',
  'VanEck',
  'yahoo_finance',
  'SMH.L',
  'LSE',
  true,
  1,
  'https://www.vaneck.com/uk/en/semiconductor-etf/',
  now(),
  'LSE USD accumulating UCITS line; distinct from the US market SMH ETF.'
)
on conflict (market_region, exchange, symbol)
do update set
  name = excluded.name,
  short_name = excluded.short_name,
  description = excluded.description,
  currency = excluded.currency,
  asset_type = excluded.asset_type,
  isin = excluded.isin,
  provider = excluded.provider,
  price_source = excluded.price_source,
  price_source_symbol = excluded.price_source_symbol,
  price_source_exchange = excluded.price_source_exchange,
  price_update_enabled = excluded.price_update_enabled,
  price_update_priority = excluded.price_update_priority,
  source_url = excluded.source_url,
  source_checked_at = excluded.source_checked_at,
  notes = excluded.notes,
  updated_at = now();
